# --!Ups
ALTER TABLE "ProjectEntry" ADD COLUMN S_STATUS VARCHAR(16) NOT NULL DEFAULT 'In Production';
CREATE INDEX IX_PROJECT_STATUS ON "ProjectEntry" (S_STATUS);

# --!Downs
DROP INDEX IX_PROJECT_STATUS;
ALTER TABLE "ProjectEntry" DROP COLUMN S_STATUS;