# --!Ups
ALTER TABLE "PlutoCommission" ADD COLUMN S_ORIGINAL_COMMISSIONER VARCHAR(512) NULL;
ALTER TABLE "PlutoCommission" ADD COLUMN T_SCHEDULED_COMPLETION TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT '2020-01-01T01:00:00Z';
ALTER TABLE "PlutoCommission" ADD COLUMN S_OWNER VARCHAR(512) NOT NULL DEFAULT 'LegacyProject';
ALTER TABLE "PlutoCommission" ADD COLUMN S_PRODUCTION_OFFICE VARCHAR(8) NOT NULL DEFAULT 'UK';
ALTER TABLE "PlutoCommission" ADD COLUMN S_NOTES TEXT NULL;
ALTER TABLE "PlutoCommission" ADD COLUMN S_ORIGINAL_TITLE TEXT NULL;
ALTER TABLE "PlutoCommission" ALTER COLUMN I_COLLECTION_ID DROP NOT NULL;
ALTER TABLE "PlutoCommission" ALTER COLUMN S_SITE_ID DROP NOT NULL;
ALTER TABLE "PlutoWorkingGroup" DROP COLUMN U_UUID;
ALTER TABLE "PlutoWorkingGroup" DROP COLUMN S_HIDE;
ALTER TABLE "PlutoWorkingGroup" ADD COLUMN B_HIDE BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "PlutoWorkingGroup" ADD COLUMN S_COMMISSIONER VARCHAR(512) NOT NULL DEFAULT 'LegacyProject';
CREATE INDEX IX_COMMISSION_OWNER ON "PlutoCommission" (S_OWNER);

# --!Downs
DROP INDEX IX_COMMISSION_OWNER;
ALTER TABLE "PlutoCommission" DROP COLUMN S_ORIGINAL_TITLE;
ALTER TABLE "PlutoCommission" DROP COLUMN S_NOTES;
ALTER TABLE "PlutoCommission" DROP COLUMN S_PRODUCTION_OFFICE;
ALTER TABLE "PlutoCommission" DROP COLUMN S_OWNER;
ALTER TABLE "PlutoCommission" DROP COLUMN T_SCHEDULED_COMPLETION;
ALTER TABLE "PlutoCommission" DROP COLUMN S_ORIGINAL_COMMISSIONER;
ALTER TABLE "PlutoCommission" ALTER COLUMN I_COLLECTION_ID SET NOT NULL;
ALTER TABLE "PlutoCommission" ALTER COLUMN S_SITE_ID SET NOT NULL;
ALTER TABLE "PlutoWorkingGroup" DROP COLUMN S_COMMISSIONER ;
ALTER TABLE "PlutoWorkingGroup" ADD COLUMN U_UUID CHARACTER VARYING NOT NULL DEFAULT '63cab052-0b60-4ebd-86c0-f8ef1bd8c574';
ALTER TABLE "PlutoWorkingGroup" DROP COLUMN B_HIDE;
ALTER TABLE "PlutoWorkingGroup" ADD COLUMN S_HIDE CHARACTER VARYING NULL;