# --!Ups
ALTER TABLE "ProjectEntry" ADD COLUMN S_PRODUCTION_OFFICE VARCHAR(8) NOT NULL DEFAULT 'UK';
CREATE INDEX IX_PROJECT_PRODUCTION_OFFICE ON "ProjectEntry" (S_PRODUCTION_OFFICE);

# --!Downs
DROP INDEX IX_PROJECT_PRODUCTION_OFFICE;
ALTER TABLE "ProjectEntry" DROP COLUMN S_PRODUCTION_OFFICE;