# -- !Ups
ALTER TABLE "ProjectEntry" ADD COLUMN T_UPDATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ProjectEntry" ALTER COLUMN T_UPDATED DROP DEFAULT;

# -- !Downs
ALTER TABLE "ProjectEntry" DROP COLUMN T_UPDATED;