# --!Ups
CREATE TABLE "AuditLog" (id INTEGER NOT NULL PRIMARY KEY,s_username CHARACTER VARYING NOT NULL, s_type CHARACTER VARYING NOT NULL, i_target_object INTEGER NOT NULL, t_at TIMESTAMP NOT NULL, s_data CHARACTER VARYING);
CREATE INDEX IX_AUDIT_USER ON "AuditLog" (s_username);
CREATE INDEX IX_AUDIT_TYPE ON "AuditLog" (s_type);
CREATE INDEX IX_AUDIT_OBJECT ON "AuditLog" (i_target_object);

CREATE SEQUENCE "AuditLog_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE "AuditLog_id_seq" OWNED BY "AuditLog".id;

ALTER TABLE ONLY "AuditLog" ALTER COLUMN id SET DEFAULT nextval('"AuditLog_id_seq"'::regclass);
# --!Downs
DROP INDEX IX_AUDIT_OBJECT;
DROP INDEX IX_AUDIT_TYPE;
DROP INDEX IX_AUDIT_USER;
DROP TABLE "AuditLog";