# --!Ups
CREATE TABLE "AuditLog" (id INTEGER PRIMARY KEY, s_username CHARACTER VARYING NOT NULL, s_type CHARACTER VARYING NOT NULL, i_target_object INTEGER NOT NULL, at TIMESTAMP NOT NULL, data CHARACTER VARYING);
CREATE INDEX IX_AUDIT_USER ON "AuditLog" (s_username);
CREATE INDEX IX_AUDIT_TYPE ON "AuditLog" (s_type);
CREATE INDEX IX_AUDIT_OBJECT ON "AuditLog" (i_target_object);

# --!Downs
DROP INDEX IX_AUDIT_OBJECT;
DROP INDEX IX_AUDIT_TYPE;
DROP INDEX IX_AUDIT_USER;
DROP TABLE "AuditLog";