# -- !Ups
CREATE TABLE "StatusChange" (
  id INTEGER NOT NULL PRIMARY KEY,
  K_PROJECT_ID INTEGER NOT NULL,
  T_TIME TIMESTAMP WITH TIME ZONE NOT NULL,
  S_USER CHARACTER VARYING NOT NULL,
  S_STATUS VARCHAR(16) NOT NULL,
  S_TITLE CHARACTER VARYING
);

CREATE SEQUENCE "StatusChange_id_seq"
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;

ALTER SEQUENCE "StatusChange_id_seq" OWNED BY "StatusChange".id;

ALTER TABLE public."StatusChange_id_seq" OWNER TO projectlocker;

ALTER TABLE "StatusChange" OWNER TO "projectlocker";

ALTER TABLE ONLY "StatusChange" ALTER COLUMN id SET DEFAULT nextval('"StatusChange_id_seq"'::regclass);

# -- !Downs
DROP TABLE "StatusChange" CASCADE;
