stages:
  - build
  - deploy

frontend:
   image: node:12.18-alpine3.12
   stage: build
   script:
   - cd frontend
   - yarn install
   - yarn test
   - yarn build:prod
   cache:
       key: ${CI_COMMIT_REF_SLUG}-node
       paths:
       - frontend/node_modules/
   artifacts:
       paths:
       - public/javascripts/bundle.js
       reports:
         junit: frontend/junit.xml

backend:
   image: registry.gitlab.com/codmill/customer-projects/guardian/pluto-core/projectlockerbuild:20190708_3
   stage: build
   services:
   - postgres:9.6
   variables:
     POSTGRES_DB: projectlocker_test
     POSTGRES_USER: projectlocker
     POSTGRES_PASSWORD: projectlocker
     POSTGRES_HOST_AUTH_METHOD: trust
     TEST_DB_URL: jdbc:postgresql://postgres:5432/projectlocker_test?user=projectlocker
     DEFAULT_DB_URL: jdbc:postgresql://postgres:5432/projectlocker?user=projectlocker
     TEST_DB_PROPERTIES_URL: jdbc:postgresql://postgres:5432/projectlocker_test?user=projectlocker&password=projectlocker&connectTimeout=30
     DEFAULT_DB_PROPERTIES_URL: jdbc:postgresql://postgres:5432/postgres?user=projectlocker&password=projectlocker
     JAVA_OPTS: -Dsbt.ivy.home=./.ivy2 -Divy.home=./.ivy2
   script:
   - if [ -d ".sbt" ]; then rm -rf ${HOME}/.sbt; mv .sbt ${HOME}; fi
   - yum -y install perl-Digest-SHA
   - sbt test:compile
   - sbt test
   - mv ${HOME}/.sbt .sbt || true
   artifacts:
     paths:
       - /tmp/pluto-core-testing.log
   cache:
       key: ${CI_COMMIT_REF_SLUG}-sbt
       paths:
       - target/
       - .sbt/
       - .ivy2/

deploy:
  image: registry.gitlab.com/codmill/customer-projects/guardian/pluto-core/projectlockerbuild:20190708_3
  stage: deploy
  services:
  - docker:19.03.11-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"  #this is mounted by the gitlab CI system so is populated from the dind service
    DOCKER_HOST: tcp://docker:2376
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_VERIFY: 1
    JAVA_OPTS: -Dsbt.ivy.home=./.ivy2 -Divy.home=./.ivy2
  script:
  - if [ -d ".sbt" ]; then rm -rf ${HOME}/.sbt; mv .sbt ${HOME}; fi
  - ls -lhd /certs
  - ls -lh /certs/*
  - mkdir ~/.docker && cp -a /certs/client/*.pem ~/.docker
  - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - yum install -y docker-ce-cli
  - docker version
  - docker login -u "${DOCKER_USER}" -p "${DOCKER_PAT}"
  - JAVA_OPTS="-Dbuild.number=${CI_PIPELINE_IID} -Ddocker.username=guardianmultimedia" sbt docker:publish
  cache:
      key: ${CI_COMMIT_REF_SLUG}-sbt
      policy: pull
      paths:
      - target/
